#!/bin/sh -e
# Rc-Local Config By KaizenVPN
# ═══════════════════════════════════════════════════════════════════
# Please do not try to change / modif this config
# This config is used for manage vpn service
# ═══════════════════════════════════════════════════════════════════
# (C) Copyright 2022 By KaizenVPN

# // Starting SSR-Server
systemctl start ssr-server > /dev/null 2>&1
exit 0
